#!/bin/bash

# Enable error reporting to the console
set -e

# Cleanup _site
rm -rf _site
mkdir _site

# Clone the remote repo to _site
git clone https://${GITHUB_TOKEN}@github.com/magento-devdocs/devdocs-for-tests.git --branch gh-pages _site
git clone https://${GITHUB_TOKEN}@github.com/magento-devdocs/m1x-devdocs.git --branch gh-pages _m1x


# Build with Jekyll to _site
bundle exec jekyll build --verbose

# Clone m1 website
mkdir _site/guides/m1x
mv _m1x/* _site/guides/m1x
rm -rf _m1x

# Setup git user details in _site
cd _site
git config user.email "dshevstov@magento.com"
git config user.name "Dima Shevtsov"

# Stage all changes
git add --all

# Commit the staged changes
git commit -a -m "Travis build #$TRAVIS_BUILD_NUMBER"

# Force push the commit to gh-pages
git push --force origin gh-pages